.travis.yml: Don't install distribute
http://python-distribute.org doesn't seem to be up anymore, which is
not surprising so long after the Distribute/Setuptools merge of
2013-06-01 [1].  This reverts 3b41da8d6 (Fix travis CI builds,
2014-02-04).

Instead, we run 'make setup' with sudo to avoid:

  $ make setup
  ...
  error: invalid command 'egg_info'

[1]: https://pythonhosted.org/setuptools/merge-faq.html#what-is-the-timeframe-of-release