Fix library test example in docs and use python3 (#1450)
The signing code has moved in thumbor and it no longer supports Python 2

% python3 -c 'from thumbor.crypto import Signer; signer = Signer("secret"); print(signer.signature("url"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'thumbor.crypto'

% python3 -c 'from libthumbor.url_signers.base64_hmac_sha1 import UrlSigner; signer = UrlSigner("secret"); print(signer.signature("url").decode("utf-8"))'
jjTzhyRdkQ3WHRCJofpLTjuYCZI=