vows.url_vows: Remove old_format reference
The argument was removed by f015a672 (Either we have unsafe or a hash,
we can't have both, 2012-07-09), which has left me with:

  $ make test
  ...
      Url vows
        Regex
          With old format

           Error in topic:
            regex() got an unexpected keyword argument 'old_format'

            Traceback (most recent call last):
              File "/.../pyvows/runner/gevent.py", line 104, in _run_setup_and_topic
                topic = topic_func(*topic_list)
              File "/.../vows/url_vows.py", line 134, in topic
                return Url.regex(old_format=True)
            TypeError: regex() got an unexpected keyword argument 'old_format'
  ...